### ISSUE TITLE
Fix writing LVH to file

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#104]
It seems that **write_lvh_to_file** method in **LETCube** class is broken.

see comments here: https://github.com/pytrip/pytrip/blob/2f2b24f7705f40d7d3013a32cfb49dc09a09f6bc/pytrip/let.py#L64

the error is:

```
  File "/home/grzanka/PycharmProjects/pytrip/pytrip/let.py", line 63, in write_lvh_to_file
    for vol, let in zip(lvh[0], lvh[1]):
TypeError: zip argument #1 must support iteration
```

lvh generated with **calculate_lvh** is linear table, has only let and doesn't have volume information

**Comment by nbassler** [comment]
This is obsoleted by #435
