### ISSUE TITLE
Fix unittests

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#11]
Remove hardcoded path to examples

**Comment by grzanka** [comment]
@nbassler can you provide some example data ?

**Comment by nbassler** [comment]
Here is a link to  
- TRiP raster scan files: `.rst`
- dose cubes `.dos`
- dosemlet cubes `.dos`
- TRiP CT files `.ctx` with corresponding headers
- treatment plans `.exec`

https://neptun.phys.au.dk/~bassler/TRiP/

a dicom file in ION-RT can be found here: https://neptun.phys.au.dk/~bassler/DKFZ/DICOM/
