### ISSUE TITLE
Strangle logger messsage printed by user application using pytrip library

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#133]
I have a simple user application using pytrip library, it tries to load non-existing file with dos cube:

```
→ cat examples/test.py 
import pytrip as pt

d = pt.DosCube()
d.read("blabla")
```

When running, it gives an output:
```
→ python examples/test.py 
No handlers could be found for logger "pytrip.cube"
Traceback (most recent call last):
  File "examples/test.py", line 4, in <module>
    d.read("blabla")
  File "/usr/local/lib/python2.7/dist-packages/pytrip/cube.py", line 545, in read
    self.read_trip_data_file(path)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/cube.py", line 614, in read_trip_data_file
    raise IOError("Could not find file " + path)
IOError: Could not find file blabla
```

Traceback is OK, but what about `No handlers could be found for logger "pytrip.cube"` message ?

**Comment by grzanka** [comment]
It looks that the problem is well-known and related to logging configuration in user application.

See for example:
https://docs.python.org/2.7/howto/logging.html#what-happens-if-no-configuration-is-provided

There are two possible solutions:
1. ask user to configure logging himself by adding to the `examples/test.py`:
```
import logging
logging.basicConfig()
```
2. add a null logging handler to pytrip/__init__.py file:
```
import logging
logging.getLogger('pytrip').addHandler(logging.NullHandler())
```

**Comment by nbassler** [comment]
prefer the null logger.

**Comment by grzanka** [comment]
I've checked and null logger works correctly.
https://lukasa.co.uk/2014/05/A_Brief_Digression_About_Logging/

Right now if there is a use-case when logger message (including error level) should be printed, then user calling his own script (which uses pytrip) will not see it.
If we add null logger user won't see it still

If user will configure the logger, message will be seen.

This task require also adding proper logger config to top-level scripts (in utils dir, like cube slicer), see https://lukasa.co.uk/2014/05/A_Brief_Digression_About_Logging/
