### ISSUE TITLE
Docs: "About" section missing

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#173]
containing
- list of current and previous developers and contributors
- could also include the build status here etc.
- Copyright notice, eventually also License
- list of reference to PyTRiP publication #172  , TRiP, SH12A

**Comment by grzanka** [comment]
Developers already there, Copyright also there, publication already there:
http://pytrip.readthedocs.io/en/stable/authors.html

Build status should also be added, but I'd see it as a separate issue - adding "developer documentation", like this one: https://pymchelper.readthedocs.io/en/stable/developer.html
