### ISSUE TITLE
Reading contours from DICOM files

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#175]
Some tools already can do it, see:
http://bio.gsi.de/DOCS/TRiP98/DOCS/dcm2trip.html
and
http://bio.gsi.de/DOCS/TRiP98/DOCS/dcm2trip.README.TXT

**Comment by grzanka** [comment]
It looks that we already have this in VdxClass, read_dicom method. Should be tested.

It would be nice to have this as a part of dicom2trip util.

**Comment by nbassler** [comment]
See #225
