### ISSUE TITLE
Cubeslice doesn't plot correctly 2x2 cube

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#183]
I've generated a VDX with a cube target using following command in TRiP98:

`makegeometry sphere / shape(box(2,2,2)) ctdim(10,10,10) ctsteps(1.0,1.0,1.0) ctnum(0) centre(2,5,7)`

It is a box centered in (2,5,7) with side of 2 mm. Box corners are: (1,4,6) ... (3,6,8).

From .vdx file we see there are only two slices:

```
slice# 7 object 1 16 64 32 32 0
#points 4 
points 16 64 16 96 48 96 48 64
slice# 8 object 1 16 64 32 32 0
#points 4 
points 16 64 16 96 48 96 48 64
```

After dividing this numbers with 16 we obtain two following contours:
- slice 7 : (1,4) (1,6) (3,6) (3,4)
- slice 8 : (1,4) (1,6) (3,6) (3,4)

I've read the vdx and created a cube with mask (-1000) using a simple script.

This gives a cube with shape 10x10x10 filled with zeros, apart from two slices:
```
Write slice number: 7/10
[[    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0 -1000 -1000     0     0     0     0     0     0     0]
 [    0 -1000 -1000     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]]
Write slice number: 8/10
[[    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0 -1000 -1000     0     0     0     0     0     0     0]
 [    0 -1000 -1000     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]]
```

Up to now everything looks reasonable.

Now the problems: cubeslice gives us following plot:
![target_008](https://cloud.githubusercontent.com/assets/7374733/20354908/df96522e-ac1f-11e6-97a9-31846fd1dd53.png)

it looks ugly. The square doesn't appear to have center in point (2,5)

Axis starts in upper right corner - why ?

Second issue - the code used to make plots is following:
```
    x = arange(xmin, xmax, cube.pixel_size)    
    y = arange(ymin, ymax, cube.pixel_size)
(...)
    x_grid, y_grid = meshgrid(x, y)
(...)
    x_max = x_grid.max()
    x_min = x_grid.min()
    y_max = y_grid.max()
    y_min = y_grid.min()
(...)
            ct_im = ax.imshow(
                ct_slice,
                cmap=plt.cm.gray,
                interpolation='bilinear',
                origin="lower",
                extent=[x_min, x_max, y_min, y_max])  # extent tells what the x and y coordinates are
```

- For this case x_min = 0.5 and x_max = 9.5 - why ?
- x_grid, y_grid - are not used anywhere - why ?
- x|y_max|min can be calculated directly from xmin and ymin and not extracted from x_grid and y_grid.

**Comment by nbassler** [comment]
- could it be some form of semantics, like beginning/end of bin vs. center of bin.
- perhaps turn interpolation off in plotting, I have the impression matplolib somtimes does strange things

**Comment by grzanka** [comment]
Interpolation is "turned off" - in fact switching to "nearest" interpolation solves the problem, see http://matplotlib.org/examples/images_contours_and_fields/interpolation_methods.html

I've also changed the way bin positions are calculated and it seems to give correct results, see:

![target_007](https://cloud.githubusercontent.com/assets/7374733/20459209/cbcd035e-aeb9-11e6-9b75-903d734316ee.png)

Once tests are done, #185 is ready to be merged.
