### ISSUE TITLE
VdxCube constructor gets a parameter which is not used

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#190]
Vdx constructor gets parameter called `content` which is not used, see https://github.com/pytrip/pytrip/blob/v1.2.1/pytrip/vdx.py#L77

```    def __init__(self, content, cube=None):
        self.vois = []
        self.cube = cube
        self.version = "1.2"
```

This leads to buggy usages, like this one: https://github.com/pytrip/pytrip/blob/v1.2.1/pytrip/utils/trip2dicom.py#L62

```
        v = pt.VdxCube(c)
```

Here `c` is assigned to `content` and not to `cube` as intended

**Comment by nbassler** [comment]
can we get rid of "content"?

**Comment by nbassler** [comment]
also mentioned in #97

**Comment by grzanka** [comment]
pytripgui PR on the way: https://github.com/pytrip/pytripgui/pull/46
