### ISSUE TITLE
Roadmap for pytrip

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#20]
In steps:
MILESTONE 1
1. separate pytrip from pytripgui #9 
each project will have separate release numbering
2. make new release of pytrip lib (not release gui)

MILESTONE 2
3. heavily refactor pytrip lib to fix all PEP8 errors (formatting)
4. add tests and docs to pytrip lib
5. make new release of pytrip lib (not release gui)

MILESTONE 3
6. fix GUI, assuming it will work with some old python version. Might be ugly but should work.

**Comment by grzanka** [comment]
@nbassler feel free to comment

**Comment by nbassler** [comment]
Yes, I think this is what we agreed on.

**Comment by nbassler** [comment]
@grzanka 
do you have specific version numbers in mind to the various milestones?

note that:
- tag pytrip-0.1.0 (very old pre-AU svn)
- tag pytrip-1.0.0 (offical GSI-friendly release)

so:
- MS 1 is IMHO 1.1.0  
- MS 2 is 1.1.1
- MS 3 is related to GUI, separate versioning?

**Comment by grzanka** [comment]
I wouldn't go up to 0.1.0 until the product is REALLY ready. In my opinion:

- MS 1 is 0.3.1 (see list of present releases: https://github.com/pytrip/pytrip/releases)
- MS 2 is 0.4.0, as new commands for user will be available (now not tested if works)
- MS 3 will not make any new release of pytrip

**Comment by nbassler** [comment]
1.0.0 was released and referred to in publications. Was working at GSI. Stepping down will make a mess...

**Comment by grzanka** [comment]
:/ ok, so what you propose makes more sense, although I do not consider 1.0 stable

**Comment by nbassler** [comment]
1.0 was actually stable and well functioning.... (on debian etch which they used at GSI).

**Comment by nbassler** [comment]
Propose to move on from 1.0.0 following standard nomenclature.
Different versioning (but same nomenclature system) for the GUI which was in sync with pytrip up until and including 1.0.0.

**Comment by grzanka** [comment]
OK, agreed.

There is however couple of release items never than what you call 1.0.0 and already released in two places:
 - https://github.com/pytrip/pytrip/releases
 - https://pypi.python.org/pypi/pytrip98

Should I remove them and make new one, called 1.1.0 ?

**Comment by nbassler** [comment]
If it is not too much a hazzle, that would be perfect.

Alternatively, we may just silently ignore these, and quickly push the new version out.

**Comment by grzanka** [comment]
I will remove them, few clicks and will be done.

**Comment by nbassler** [comment]
Let's create the milestones according to this discussion, so this issue can be closed.

**Comment by nbassler** [comment]
@grzanka  I think this one is done and can be closed.
