### ISSUE TITLE
cubeslice from-to behaviour is not as expected

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#200]
- would expect [FROM:TO] but if FROM==TO then no output is made. if they differ then [FROM:TO[
- also counting the slices outputted starts at zero (0/102) and terminates one index earlier than expected (101/102)

**Comment by nbassler** [comment]
I propose to let slice numbers start in 1. DICOM uses asbolute positions rather than slices. For users it may lead to mistakes that there are 107 slices but the last slice is called 106.

**Comment by grzanka** [comment]
What about including in the filename also z position (i.e. in 2.3f [mm] format ) ?

**Comment by nbassler** [comment]
think it would be better to have it imprinted into the figure, else the fnames get so bloated, what do you think?

**Comment by grzanka** [comment]
Good idea - title ?
