### ISSUE TITLE
PyTRiP generated CTX cubes cannot be loaded by TRiP98

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#201]
```
import pytrip as pt

c = CtxCube()
c.read("shieldhit/res/TST000/TST000000.ctx)
c.set_byte_order("little")
c.write("TST000000.ctx")
```

problem is, that the written header file says ```version 1.2``` which TRiP will not load. Setting this to ```version 1.4``` fixes this, and all loads fine by TRiP98 (byte order is correct too, btw).

**Comment by grzanka** [comment]
I haven't checked import into TRiP98, but I see that in contrary to what @nbassler says, the header is generated with `version 1.4`

It looks it was like that at least from pytrip version 1.1.0, see https://github.com/pytrip/pytrip/blob/v1.1.0/pytrip/cube.py#L656

```
# grzanka at dell in ~/PycharmProjects/pytrip on git:master ✖︎ [21:52:37]
→ PYTHONPATH=. python3 tests/issue_201.py 
1.2.3.post.dev1

# grzanka at dell in ~/PycharmProjects/pytrip on git:master ✖︎ [21:53:58]
→ cat tests/issue_201.py 
import pytrip as pt

print(pt.__version__)
c = pt.CtxCube()
c.read("/home/grzanka/PycharmProjects/shieldhit/res/TST000/TST000000.ctx")
c.set_byteorder("little")
c.write("TST000000.ctx")
# grzanka at dell in ~/PycharmProjects/pytrip on git:master ✖︎ [21:54:05]
→ cat TST000000.hed 
version 1.4
modality ct
(...)
```

**Comment by nbassler** [comment]
I think the version was retained header of TST00000. I will check again.

**Comment by grzanka** [comment]
In my case in this operation (reading and writing CT cube) almost all items in header are consistent in input and output files. Tested with header files version 1.4 (i.e. TST000/TST000000.ctx) and 1.2 (i.e. TST003).

Differences are:
 - if `slice_distance` is integer in input file, then it's saved as float in output file.
 - if input file contains `z_table` then its discarded and not saved in output file

**Comment by nbassler** [comment]
I checked again.
It is simply keeping the version which is found in the original file. I think this is proper behaviour.
So this can be closed.
