### ISSUE TITLE
Improve handling of LET cubes in cubeslicer

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#212]
Following https://github.com/pytrip/pytrip/issues/66#issuecomment-268022764

**Comment by nbassler** [comment]
think that was closed in #199

**Comment by grzanka** [comment]
I wanted to avoid hardcoding parts of file extension ("dosemlet") in many different places of the code, thus this change.

This PR will fix also problem:
```
AttributeError: 'Namespace' object has no attribute 'dos'
```
mentioned in issue #198

**Comment by nbassler** [comment]
ok
