### ISSUE TITLE
Add DICOM-RT test data

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#22]
propose to include this:

http://neptun.phys.au.dk/~bassler/DKFZ/DICOM/

**Comment by nbassler** [comment]
@grzanka: Sufficient to refer to test data in README.md?

**Comment by grzanka** [comment]
@nbassler not sufficient. I'd like to include some automatic tests if .dicom files are properly imported and exported. If dicom files are small I'd put them in `tests/res`, otherwise should be downloaded on demand

**Comment by nbassler** [comment]
Sooo.... we need a .dcm gzipper as well

**Comment by nbassler** [comment]
Ooops.

**Comment by grzanka** [comment]
Yes, .dcm gzipper would be good to have. New issue for that

**Comment by nbassler** [comment]
More data here:
https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/

**Comment by nbassler** [comment]
@grzanka What must be done to close this issue?

**Comment by grzanka** [comment]
Test data should be added to some of ours repository (and used by some tests):
 - if small (<10MB) then putting the files into `pytrip/test` should be ok
 - if big (>10MB) then a separate repo should be created. We could consider using Git LFS storage. GitHub supports that, but there might be some quotas, 1 GB is mentioned here: https://github.com/blog/1986-announcing-git-large-file-storage-lfs

**Comment by nbassler** [comment]
"Every user and organization on GitHub.com with Git LFS enabled will begin with 1 GB of free file storage and a monthly bandwidth quota of 1 GB."

with all our testing, that limit is quickly hit. Upload to neptun.phys.au.dk instead? It is fairly stable.
