### ISSUE TITLE
dicom2trip does not convert structures

### ISSUE THREAD

**Issue by Tibazz** [pytrip/pytrip#222]
attempted with a pinnacle created dicom file found here:
https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/pinnacle3-9.9-phantom/
``` dicom2trip dicomdir/  foobar000```

produces only the .ctx files

**Comment by grzanka** [comment]
Can you provide information on the pytrip version used (type dicom2trip --version), OS and Python version ?

**Comment by nbassler** [comment]
related: #190
