### ISSUE TITLE
Add versioneer to .gitignore

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#228]

**Comment by nbassler** [comment]
I think this is rather a general versioneer issue.

How to reproduce:

1) Checkout some branch pytrip/pymchelper/pytripgui ....
2) Try to run locally (```PYTHONPATH=. python3 foobar```)
3) realize versioneer is missing: ```versioneer install```
4) Things now run fine locally, make changes to some files 
5) stage your change filed and commit it

and then ... surprise ... versioneer has apparently stanges some other files as well, which are commited too.

This happens very silently, and I often forget to unstage the files.

Consequence: at the next push to origin versioneer garbage is uploaded.

Happend several times to me.
how

**Comment by grzanka** [comment]
You are right - versioneer is forcing GIT to add these files, see: https://github.com/warner/python-versioneer/blob/master/src/git/install.py#L39

.gitignore can partially solve this problem by preventing versioneer from adding two files: `versioneer.py` and `_version.py`, but still the problem will be with `__init__.py` and `MANIFEST.in`

```
→ versioneer install
versioneer.py (0.18) installed into local tree
Now running 'versioneer.py setup' to install the generated files..
 creating pytrip/_version.py
 appending to pytrip/__init__.py
 appending 'versioneer.py' to MANIFEST.in
 appending versionfile_source ('pytrip/_version.py') to MANIFEST.in
The following paths are ignored by one of your .gitignore files:
pytrip/_version.py
versioneer.py
Use -f if you really want to add them.
```

**Comment by grzanka** [comment]
The solution I see now is to provide a script (and commit it into the repo) which will:

1. run `versioneer install`
2. do upstaging of the files added by versioneer
