### ISSUE TITLE
RayStation cannot load PyTRiP generated dicoms

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#237]
Laconic error message "No conversion for this enum type."
No diagnostic files outputted.

**Comment by TokePrintz** [comment]
I am not so sure now when I read this error message that the issue has to do with the order of the slices (see comment in #193), but I know nothing about how RayStation works, so I could be wrong...

**Comment by nbassler** [comment]
think the bad line is this one:
```
    if "images" in data:
        data["images"].sort(key=compare_dicom_key)
```

**Comment by grzanka** [comment]
@nbassler the code snippet you mentioned:

```
    if "images" in data:
        data["images"].sort(key=compare_dicom_key)
```

belongs to `read_dicom_folder` which is used when converting DICOM->TRiP98,
not when converting from TRiP98 to DICOM.

**Comment by nbassler** [comment]
But the images were originally converted from DICOM to TRiP.

**Comment by nbassler** [comment]
ok, the key is a float, not a str. So it cannot be there, I'm convinced now.

**Comment by grzanka** [comment]
I've also checked `SliceLocation` - it has DICOM type `DS`, see https://www.dabsoft.ch/dicom/6/6/#(0020,1041)

`DS` means decimal string, so it looks OK, see ftp://dicom.nema.org/medical/DICOM/2013/output/chtml/part05/sect_6.2.html

_A string of characters representing either a fixed point number or a floating point number. A fixed point number shall contain only the characters 0-9 with an optional leading "+" or "-" and an optional "." to mark the decimal point. A floating point number shall be conveyed as defined in ANSI X3.9, with an "E" or "e" to indicate the start of the exponent. Decimal Strings may be padded with leading or trailing spaces. Embedded spaces are not allowed._

**Comment by nbassler** [comment]
The issue was PatientsSex mapped to "0" (zero) which is not in the enum lists. It should be either '' (unspecified), 'O' (other), 'M' (male) or 'F' (female)

defaulting to '' (unspecified).
