### ISSUE TITLE
converting TRiP to DiCOM sets bad pixel size

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#245]
as discussed in https://github.com/pytrip/pytripgui/issues/58

**Comment by nbassler** [comment]
seems to work with last commit.

Converted from TRiP to DICOM:
![screenshot_2017-02-15_18-43-03](https://cloud.githubusercontent.com/assets/7140398/22987383/d6d7eedc-f3ae-11e6-9ab3-800e243caa2e.png)

**Comment by nbassler** [comment]
@asg16 @TokePrintz does the issue persist since 1.3.1 ?
I have trouble reproducing the error.

**Comment by nbassler** [comment]
@asg16 @TokePrintz what I mean, did you really check what version you used for converting? 
```trip2dicom -V```
 should give the answer.

Sometimes you may have multiple versions pytrip installed if you use pip (e.g. if you install both as root and as a user)

**Comment by nbassler** [comment]
tried converting shieldhit/res/TST000/.vdx +ctx where vdx is in version 2.0. Resulting dicom is correctly displayed in pytripgui (and the pixelsize != 1.0 in the .hed)

**Comment by nbassler** [comment]
http://dicom.nema.org/medical/dicom/2016c/output/chtml/part03/sect_10.7.html#sect_10.7.1.1

**Comment by TokePrintz** [comment]
![jet01_shifted](https://cloud.githubusercontent.com/assets/22157203/23229133/6d4b3a96-f93f-11e6-9b3f-6ab5ae95b85c.png)
Okay, I generated the DICOM files from the same .ctx. and .vdx sent to Niels using pytrip on the Krakow cluster and put them into Eclipse...and the contours look still wrong! It could be a matter of the voxel size not being taken into account, like Alina proposed. 
The strange thing is that it IS taken into account in the code and that Niels cannot reproduce the error. The way to debug this issue might be to figure out the difference between Niels' files and Alinas. Alinas files are originally DICOM files made into .ctx and .vdx by dicom2trip some years back. They have been planned upon and displayed in TRiP without these contour errors. Could it be that this conversion back and forth creates errors as I think Leszek proposed? Or is there maybe some difference in the file format of the vdx-file of Niels and the one of Alina? Alinas .vdx are all version 1.2.

**Comment by TokePrintz** [comment]
I add that this issue is very urgent to solve. As long as the contours are wrong, we cannot start planning, which in return makes it difficult to finish the abstract before the abstract deadlines of BiGART (March 22nd) and DGMP (March 31st).

@nbassler maybe you can tell a bit about the .ctx and .vdx files you are using, which are working? Which version are they? And from where do they originate? If originally they were DICOM too, how were they converted to TRiP-format?

**Comment by grzanka** [comment]
@TokePrintz what about sharing our files in some google drive folder ?
What is still unclear to me is what are the units (scaling) of contours in .vdx files in format 1.2 and 2.0.

**Comment by TokePrintz** [comment]
Niels already has our test files. I have just now also sent them to you (using google drive). I must empathize however that these files are to be deleted after testing (since they are actually not for sharing)!!!

The "scaling" are in units of mm. As Alina wrote in pytrip/pytripgui#58, the length of one voxel in the case of her test patient is not 1 mm but 0.9375 mm, which seems not to be taken into account. Therefore all the points of the contours are shifted and are too large. She confirmed this with a simple square contour.  

@grzanka you wrote in the other thread smth like "I confirm that no scaling with pixel size is applied when generating .vdx files in 2.0 format." But @nbassler is using 2.0 format and cannot reproduce the error?!? Can it be simply that in Niels' case, the voxel size was 1 mm by chance?

**Comment by nbassler** [comment]
I converted dicom->trip->dicom for a pizelsize != 1 case, and had no problems. 
I will try to find time for this issue this weekend.

**Comment by TokePrintz** [comment]
If the problem is indeed missing scaling of the contour points with pixelsize, then you will never encounter any problems with your file with pixelsize != 1. First step would be to see if the error can be reproduced using the files Alina provided to zoom in on the bug:-)

**Comment by nbassler** [comment]
Tried the files from @asg16

```
pytrip$ PYTHONPATH=. python3 pytrip/utils/trip2dicom.py cube dcmcube
Convert CT images
Convert structures
Done
```

Then:

bassler@baslup:~/Projects/pytrip$ PYTHONPATH=. python3
>>> import pytrip as pt
>>> dcm = pt.dicomhelper.read_dicom_folder("dcmcube/")
>>> c = pt.CtxCube()
>>> c.read_dicom(dcm)
>>> c.pixel_size
0.9375
>>> 
```

So this seems OK.
However, opening the file in PyTRiPgui I see 
- a scaling issue
- issue https://github.com/pytrip/pytripgui/issues/58 which I think is a PyTRiP issue.

**Comment by TokePrintz** [comment]
I think both these issues are PyTRiP issues and not PyTRiP-GUI issues. At least the scaling we see in Eclipse too.

**Comment by nbassler** [comment]
The original TRiP files I received by @asg16 is also displayed wrong in PyTRiPGUI. I.e. the structures do not match the CT.

**Comment by TokePrintz** [comment]
So: 
1) Turning Alinas DICOM into .vdx and .ctx using dcm2trip returns voxelplan format 1.2 and wrongly displayed contours in pytrip-GUI (and therefore also in Eclipse when transformed back into DICOM by pytrip). However these voxelplan files work in TRiP.
2) Turning Alinas DICOM into .vdx and .ctx using pytrip returns voxelplan format 1.4 and correctly displaued contours in pytrip-GUI. But then when transformed back into DICOM, import of these files seem fail in Eclipse (#257)

Further tests will be done later today...

**Comment by nbassler** [comment]
.... 1:0 for dicom2trip ;)

**Comment by asg16** [comment]
Hi!
Hahaha! It is not really 1:0...The vdx format 2.0 (1.4 in the header) offers coordinates which are already in mm, whereas the format 1.2 gives the contour coordinates in voxel positions. Each number in each line "points xxxx yyyy....." needs to be scaled with a division by 16, and multiplied by the voxel size in mm to convert the coordinates to mm.....
That is why we find the scaling problem only with the contours with format of the 1.2 version.  Where you downscale by 16, at the same step, you have to multiply by the voxel size.

**Comment by nbassler** [comment]
ok, suggest:
- when converting from DICOM, always use more recent format (2.0) for VDX
- only keep the legacy 1.2 vdx contour voxel number compability for READING legacy .vdx files
- @grzanka we should agree that all contour points are stored in absolute coordinates incl. any offsets. Right now several systems coexist.

**Comment by TokePrintz** [comment]
It could be in this piece of the code - where coordinates are divided with 16 - that they are at the same time divided by the pixelsize read from .hed.  

`    def read_vdx_old(self, slice_number, xy_line):
        """ Reads a single Contour from Voxelplan .vdx data from 'content' and appends it to self.contour data
        VDX format 1.2.
        :params slice_number: list of numbers (as characters) with slice number
        :params xy_line: list of numbers (as characters) representing X and Y coordinates of a contour
        """

        # and example of xy_line: 3021 4761 2994 4899 2916 5015
        xy_pairs = [xy_line[i:i + 2] for i in range(0, len(xy_line), 2)]  # make list of pairs
        for x, y in xy_pairs:
            # TRiP98 saves X,Y coordinates as integers, to get [mm] they needs to be divided by 16
            self.contour.append([float(x) / 16.0, float(y) / 16.0, float(slice_number)])`

**Comment by TokePrintz** [comment]
(sry, somehow I have yet to figure out how to properly paste in code)
