### ISSUE TITLE
fix RTSS filenames when converting to dicom

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#247]
Currently:
```
CT.PYTRIP.10.dcm
CT.PYTRIP.11.dcm
CT.PYTRIP.12.dcm
(...)
CT.PYTRIP.80.dcm
CT.PYTRIP.8.dcm
CT.PYTRIP.9.dcm
rtss.dcm
```

**Comment by grzanka** [comment]
I think better would be (at least for CT):

```
CT.PYTRIP.0008.dcm
CT.PYTRIP.0009.dcm
CT.PYTRIP.0010.dcm
CT.PYTRIP.0011.dcm
CT.PYTRIP.0012.dcm
(...)
CT.PYTRIP.0080.dcm
```

**Comment by nbassler** [comment]
yes, but do other vendors do that? 
Is a different issue anyway, this was only addressing the VDX structure filename...

**Comment by grzanka** [comment]
You are right - not all vendors do that.

I found a hint here: http://cs.jhu.edu/~sdoshi/jhuisi650/papers/dicomsecuritychap11.pdf

> 2. The “1.2.840…” prefix is used in all standard DICOM identifier (UID) strings,
> and its presence in a file confirms that we are dealing with DICOM. Often,
> DICOM files are named after their image UIDs, in which case, DICOM file
> names begin with the same prefix.

If you look at https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/eclipse-8.1.20-phantom-breast/Original/  DICOMs are named after SOPInstanceUID.

```# grzanka at nz61-6 in ~/PycharmProjects/data/eclipse-8.1.20-phantom-breast/Original [19:07:18]
→ dcmdump CT.1.2.840.113619.2.55.3.671756986.106.1316467036.362.9.dcm | grep 1316467036                                         ~/PycharmProjects/data/eclipse-8.1.20-phantom-breast/Original
(0002,0003) UI [1.2.840.113619.2.55.3.671756986.106.1316467036.362.9] #  52, 1 MediaStorageSOPInstanceUID
(0008,0018) UI [1.2.840.113619.2.55.3.671756986.106.1316467036.362.9] #  52, 1 SOPInstanceUID
(0020,000d) UI [1.2.840.113619.2.55.3.671756986.106.1316467036.356] #  50, 1 StudyInstanceUID
(0020,000e) UI [1.2.840.113619.2.55.3.671756986.106.1316467036.361] #  50, 1 SeriesInstanceUID
(0020,0052) UI [1.2.840.113619.2.55.3.671756986.106.1316467036.358.13445.1] #  58, 1 FrameOfReferenceUID
```

**Comment by grzanka** [comment]
I've checked two examples: one for Pinnacle and one for Eclipse. There the pattern is `'CT.' + SOPInstanceUID + '.dcm'`. 
Xio adds some additional suffix https://subversion.assembla.com/svn/slicerrt/trunk/SlicerRt/data/xio-4.64-phantom-prostate-beams-imrt/

**Comment by nbassler** [comment]
HIT has a very different pattern too, I discussed this with @okejdokej and we ended up with the CT.PYTRIP.%d.dcm pattern for now. But again, this thread was merely dealing with the RTSS filename.
