### ISSUE TITLE
Raystation RTStruct - bad slice mapping

### ISSUE THREAD

**Issue by okejdokej** [pytrip/pytrip#250]
It was a file converted from DICOM to TRiP and back. And this is the error from RayStation. (Error number 2)
It was a Pinnacle IMRT DICOM file from the usual test files we use. (PyTRiP 1.3.1)
![image](https://cloud.githubusercontent.com/assets/24609213/23018172/47b3bb34-f43d-11e6-9db5-8662275b6dda.png)

**Comment by nbassler** [comment]
https://github.com/pytrip/pytripgui/issues/58

**Comment by nbassler** [comment]
This affects not only RayStation, but also PyTRiPGUI and probably all other viewers.

**Comment by nbassler** [comment]
todo:
- [ ] remove pos_to_indices
- [ ] remove get_value_at
- [ ] make ztable mandatory (create linearly during initialization if absent)
- [ ] refactor slice_to_z() to rely on ztable instead of linear lookup function

**Comment by nbassler** [comment]
converting dicom2trip removes the z_table.
converting back to dicom, repositions all slices linearly.
Contour coordinates are retained however, but coords dont match anymore if z_table was nonequidistant.
