### ISSUE TITLE
Eclipse errors and warnings when importing DICOM set, generated from TRiP files format 1.4

### ISSUE THREAD

**Issue by TokePrintz** [pytrip/pytrip#257]
![error_jet03](https://cloud.githubusercontent.com/assets/22157203/23257784/9e3d95aa-f9c5-11e6-8844-6f4458f16b1f.png)
I was trying to test different formats of TRiP files (.vdx,.hed,.ctx) being converted into DICOM using pytrip 1.3.1 in relation to #245. 
I had some files in format 1.4 originally converted from DICOM into TRiP format around two years ago using the then-version of pytrip. When I converted these back into DICOM and imported them in Eclipse, I got the above shown errors and warnings and the import failed (there are more warnings not seen in the screen window but they are identical to the last couple of warnings). It is the first time I see these errors. Normally we just get some warnings and the import works.

To recap, the difference between the files tested until now and the warnings/errors they give: 
1) Niels' are generated from TRiP format 2.0. Where they originally DICOM? No warnings, no errors, import works.
2) Alinas files are generated from TRiP format 1.2 from DICOM originally converted into TRiP format using dcm2trip. Some warnings #255, no errors, import works.    
3) In this case files are generated from TRiP format 1.4 from DICOM originally converted into TRiP format using an older 2015 version of pytripgui. We get warnings, errors and the import fails. 
An important note is that the original DICOM Alina uses and the ones I use are from the same place. Only the TRiP format (and the way they were made into this format) are different.

Now it remains to be figured out if this issue comes from the difference in format or if the older version of pytrip had bugs when generating TRiP files?

**Comment by nbassler** [comment]
BTW, @TokePrintz do you have anyone in house who knows more about the various VDX versions? Would be useful to record them in a wiki.

**Comment by TokePrintz** [comment]
Well, in-house maybe not. Possibly Gheorghe Iancu. Outside of "the house" Uli Weber comes to mind. He is on top of that not sitting many meters away from MK, who would know for sure!:-)

**Comment by TokePrintz** [comment]
I couldn't find any documentation on the TRiP homepage about this.

**Comment by nbassler** [comment]
@TokePrintz thought you might have some of the TRiP gurus nearby (like Uli)

**Comment by TokePrintz** [comment]
I can now confirm for more cases that when I take a DICOM set, generate it into voxelplan files with pytrip, generate again a DICOM set from these voxelplan files with pytrip and try to import in Eclipse, I get the errors and warnings listed above and the import fails.
