### ISSUE TITLE
CT slices and contours separated with two different patient IDs in 1.3.2

### ISSUE THREAD

**Issue by TokePrintz** [pytrip/pytrip#263]
![jet02_whytwopatients](https://cloud.githubusercontent.com/assets/22157203/23343370/af1f95a6-fc6a-11e6-9100-7fd36fad8ceb.png)

I hate to be the party-pooper  but I think there is a bug in the newest version (1.3.2) when voxelplan is generated into DICOM. 

The trip2dicom command gives the following error in the terminal: "WARNING: pytrip.vdx:Reading .vdx in 1.2 format: no CTX cube associated, setting pixel_size to 1.0." The DICOM is although still generated and all looks okay. But when importing the directory with the DICOM in Eclipse, it sees "two patients" (see image). One of them is the CT data, the other is the contour. The contour has the new patient ID that was implemented in 1.3.2, while the CT data has no patient ID (and Eclipse therefore demands you come up with one with import). By first importing the CT data and setting the patient ID to that which the contour has and then importing the contour on top of the CT afterwards, one can manage to get both the CT and the contour imported. BUT since pixel_size was set to 1.0 as the warning in the terminal said, our contours are STILL shifted and placed wrongly, as in version 1.3.1.

Can it be that the new fix for the patient ID is somehow only working for the .vdx and then pytrip doesn't find a matching .ctx and sets a default pixel_size value? 
Also, in a situation like this, maybe pytrip could ask the user for a pixel_size?

**Comment by nbassler** [comment]
Yeah, that is the issue, when the developers have not access to the test machinery.

But until then, you should be aware of you can change the PatientID yourself by setting the attribute manually.

**Comment by nbassler** [comment]
@TokePrintz 
can you give a bit more information on what exactly you did?

**Comment by TokePrintz** [comment]
@nbassler I am basically always just running a command that @grzanka wrote in an explanatory email to Alina some weeks back:  trip2dicom <dir_with_voxelplan_files>/<name_of_voxelfiles>.hed <some_output_dir>. Then it returns "Convert CT images, Convert structures, Done" (and in this case then also the warnings, some large amount of times which might be the slice number).

So to understand it correctly: Can I set a patient ID myself to the vdx and ctx before giving the trip2dicom command? If yes, I can try to see if that fixes the problem.
Is my assumption correct that pytrip sets the pixel_size to 1.0 because it didn't find it in the header (or the ctx)?

**Comment by grzanka** [comment]
@TokePrintz on which files are you running `trip2dicom` command ? can you share these files  or point to exact file location ?

To change patient id you need to write a script, similar to http://pytrip.readthedocs.io/en/stable/examples.html#example-01-handling-structures

**Comment by TokePrintz** [comment]
It is the very same test patient we have been using all the time, which I shared using google drive. 
(I furthermore always do the same test for a similar patient from the same cohort and always with the same result).
