### ISSUE TITLE
Change in SOPInstanceUID to allow multiple CT and contour data sets to be loaded under the same patient

### ISSUE THREAD

**Issue by asg16** [pytrip/pytrip#292]
Hallo again! I tried to load a second CT under an already existing patient in Eclipse, after fixing manually the issue with the StudyInstanceUID, and it did not work. This is because so far, you are building the SOPInstanceUID for each CT slice based on a fixed string:
"SOPInstanceUID = '2.16.1.113662.2.12.0.3057.1241703565', and then you add the CT slice number. 
Eclipse complains that you are trying to import the same object again.
This tag has to be different for each CT dataset (the string before the slice number needs to change). If I figure out what needs to be the structure of this tag, I will let you know. For now, it would be enough if it is just "different" in a general sense (e.g. the last portion could be a random number, or a time stamp).

**Comment by grzanka** [comment]
I can include it in PR #293 if it goes good direction

**Comment by grzanka** [comment]
Are there any requirement for prefix of SOPInstanceUID ?
