### ISSUE TITLE
New class: RBECube

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#307]
to hold actual RBE values. Needed by models to be implemented later.

**Comment by grzanka** [comment]
http://bio.gsi.de/DOCS/TRiP98/PRO/DOCS/trip98cmddose.html

> write
> Writes the current dose cube(s) as specified by file. Naming convention:
> 
> contains the extension .DOS or .dos:
> for the physical dose. For the biological dose: .DOS and .HED, where is "bio", "rbe" and "svv".
> otherwise:
> .dos and .hed, where is "phys", "bio", "rbe" or "svv".

Would this be compatible with RBE TRiP98 cubes ?

I see that new TRiP98 can extract them:
http://bio.gsi.de/DOCS/TRiP98/PRO/DOCS/trip98cmddose.html#rbe

**Comment by nbassler** [comment]
I guess so, yes. Compability could be ensured by read() and write() methods.

This also defines the suffix issue then. (```.rbe.dos```, I guess)

**Comment by nbassler** [comment]
Closed via #316
