### ISSUE TITLE
New class: CellCube

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#310]
to hold cells. 

each voxel holds then a tuple, containing:
- number of cells in voxel
- alpha_photons
- beta_photons
- pO2 status [mmHg]

however this is very memory intensive. Surely this can be made smarter..

**Comment by grzanka** [comment]
do you mean "biological cells" ?
will this be an absolute or relative value ?

**Comment by nbassler** [comment]
number of cells is an absolute number for each voxel, I thought. (Will be useful for modeling using fractionation etc.)

**Comment by grzanka** [comment]
`cell` can be very confusing as it is very often use in IT world, can you prefix it with Bio or sth else ?

**Comment by nbassler** [comment]
BioCube() could may be confused with *.bio.dos which is produced by RBECube() ?

**Comment by grzanka** [comment]
CytologyCube ?

**Comment by nbassler** [comment]
TissueCube?

**Comment by grzanka** [comment]
looks OK, but seems a bit more general than Cell

**Comment by nbassler** [comment]
But else my vote would still rather be CellCube. ("Bio" is also not referring to that this cube fabricated without pesticides, if people really want to misunderstand something, there is plenty of opportunities to do so.)
TissueCube() would be OK in the sense that it also may hold several tissue types (i.e. different alpha beta values). Maybe it could also be expanded with future tissue relevant parameters, beyond alpha/beta/pO2.

Should there be an alternative way of initializing the cube, if e.g. pO2 is the same value for all voxels to be more memory efficient?

**Comment by nbassler** [comment]
maybe ask @TokePrintz about his opinion...

**Comment by TokePrintz** [comment]
Well, this for sure didn't help: http://www.thesaurus.com/browse/tissue and http://www.thesaurus.com/browse/cell :-)
TissueCube() for me makes sense. Maybe more than CellCube(). I would avoid BioCube since it strikes me as somehow misleading. 
Or else Alina proposes HistoCube() from "histology".

**Comment by TokePrintz** [comment]
(ups, wrong button)

**Comment by nbassler** [comment]
@TokePrintz  Alina needs to confirm her invitation to the PyTRiP group.

**Comment by nbassler** [comment]
@grzanka alternatively, instead of introducing all these new Classes, one could also simply work with the top-level Cube class? Techinically the type is the same anyway for all of these.

**Comment by nbassler** [comment]
parameters such as SF alpha beta could be passed to functions as a single value or a cube array.
