### ISSUE TITLE
can DDD class work with less than three .ddd input files?

### ISSUE THREAD

**Issue by Tibazz** [pytrip/pytrip#325]
https://github.com/pytrip/pytrip/blob/master/pytrip/ddd.py#L135

interpolate.splrep probably requires at least 3 points, otherwise it displays error:
```TypeError: m > k must hold```

**Comment by grzanka** [comment]
Provide a code snippet in which you want to use this DDD class.

**Comment by Tibazz** [comment]
The issue is related to:
```self.max_dist = interpolate.splrep(max_dist[:, 0], max_dist[:, 1], s=0)```

since i only have 2 .ddd files for energies 130 and 140 MeV  in my directory the max_dist list only has two available points which i think makes the spline interpolation fail. 

thus running
`you = pt.DDD()`
`you.load_ddd('C:/Users/Tibazz/Google Drive/Universitetet/Master Project/WORK/DDD/*)` 

yields: 

 ``File "C:\Users\Tibazz\Google Drive\Universitetet\Master Project\WORK\PyTrip98.py", line 140, in load_ddd
    self.max_dist = interpolate.splrep(max_dist[:, 0], max_dist[:, 1], s=0)
  File "C:\Users\Tibazz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scipy\interpolate\fitpack.py", line 278, in splrep
    res = _impl.splrep(x, y, w, xb, xe, k, task, s, t, full_output, per, quiet)
  File "C:\Users\Tibazz\AppData\Local\Programs\Python\Python36-32\lib\site-packages\scipy\interpolate\_fitpack_impl.py", line 464, in splrep
    raise TypeError('m > k must hold')
TypeError: m > k must hold ``

**Comment by nbassler** [comment]
suggestions:
- do not interpolate if only one .ddd file is provided
- if two ddd files are provided, switch to linear interpolation

**Comment by grzanka** [comment]
See PR #339
