### ISSUE TITLE
Appveyor build fails with "unable to create file pytrip/models/aux.py"

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#327]
See https://ci.appveyor.com/project/grzanka/pytrip/build/1.0.859/job/5ge6iq9ny5cvo3gu

```
Build started
set PATH=%PYTHON_ROOT%;%PYTHON_ROOT%\Scripts;%PATH%
set PATH=%MINICONDAPATH%\Scripts;%PATH%
git config --system http.sslcainfo "C:\Program Files\Git\mingw64\ssl\certs\ca-bundle.crt"
python -V
Python 2.7.13
python -c "import struct;print(8 * struct.calcsize('P'))"
32
git clone -q --branch=feature/318-newyear https://github.com/pytrip/pytrip.git C:\projects\pytrip
error: unable to create file pytrip/models/aux.py: No such file or directory
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by grzanka** [comment]
@nbassler 
Funny thing. We cannot name the file aux.py. If we do like that Windows users will not be able to do `git clone`. I've tried to clone the repo locally on my Windows and I am unable to do that.

Here I've found the hint http://stackoverflow.com/questions/3689137/error-git-checkout-index-unable-to-create-file:
> The answer should be:we can't create a file named aux.c in windows!
> 
> See http://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx Do not use the following reserved device names for the name of a file: CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended. For more information, see Namespaces.

I recommend to rename aux,py to sth else under Linux. Any suggestion for new name ? auxiliary.py ?

**Comment by nbassler** [comment]
haha... that is funny. Propositions:
- extra.py
- tools.py
- common.py
- ?

**Comment by grzanka** [comment]
`extra.py` seems OK.
