### ISSUE TITLE
Closed contour issue

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#330]
I took a look at issue https://github.com/pytrip/pytripgui/issues/72 and found the source of the error.

Issue is, whether the last point in a contour should be repeated at PyTRiP level or not.
Observations:
- **Old VDX format:** repeats last point to close contour
- **New VDX format:** repeats last point to close contour
- **DICOM:** does **not** repeat last point

I would like to have consistent behaviour, so either we repeat the last point in the contour object or not, no matter how the original contour data were loaded from VDX or DICOM.
So:
1) choose to repeat last point at PyTRiP Contour() level:
  -- requires slight modification of dicom read/write
2) choose **not** to repeat last point at PyTRiP Contour() level:
  -- requires slight adjustment of VDX readers and writers
  -- requires slight adjustment of PyTRiPGUI

I might even prefer 2) just to avoid messing around with DICOM and from the philosophy of staying close to DICOM if possible.

Also, I think it would give nicer code when implementing POIs (see https://github.com/pytrip/pytripgui/issues/63 and #314 )

**Comment by grzanka** [comment]
Yes, I agree option 2 seems better in terms of code layout. It should be also followed with clean comments in appriopriate methods.

**Comment by grzanka** [comment]
See also https://github.com/pytrip/pytripgui/issues/96

**Comment by nbassler** [comment]
closed via #332
