### ISSUE TITLE
Class DDD not callable after installing PyTrip98 via pip on Windows 10, Python version 3.6

### ISSUE THREAD

**Issue by Tibazz** [pytrip/pytrip#335]
I simply can not find and use the DDD.py functions, not even using dir(pt).

```dir(pt)```
``` ['CTImages', 'CtxCube', 'Cube', 'DensityCube', 'DosCube', 'LETCube', 'Rst', 'VdxCube', 'Voi', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_version', 'ctimage', 'ctx', 'cube', 'dicomhelper', 'dos', 'error', 'file_parser', 'let', 'logging', 'paths', 'raster', 'read_dicom_folder', 'res', 'vdx'] ```

**Comment by grzanka** [comment]
Try this way:

```
>>> from pytrip.ddd import DDD
>>> help(DDD)

>>> dir(DDD)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'get_ddd_by_energy', 'get_ddd_data', 'get_ddd_grid', 'get_dist', 'load_ddd']
```

**Comment by Tibazz** [comment]
That works 👍

**Comment by grzanka** [comment]
BTW - new implementation of DDD is on the way, see https://github.com/pytrip/pytrip/pull/339
Can you comment on it ?
