### ISSUE TITLE
tripexecuter: understands only few ions

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#346]
pytrip.tripexecuter currently only understands 'H' 'C' 'O' and 'Ne'

We need some proper handling here for e.g. He-3, He-4 and similar.

**Comment by nbassler** [comment]
remark on the side line:
attempting to load multiple DDD file species in TRiP98, yields:
```
TRiP98> ddd "/home/bassler/TRiP98/base/DATA/DDD/1H/RF3MM/1H*" /read 
TRiP98> ddd "/home/bassler/TRiP98/base/DATA/DDD/12C/RF3MM/12C*" /read 
<E> trpddd.c(PrimDDDAdd): sorry, no multiple ions in this version
<E> trpddd.c(PrimRead) /home/bassler/TRiP98/base/DATA/DDD/12C/RF3MM/12C.H2O.MeV05000.ddd: sorry, no multiple ions in this version
<E> trpcmdddd.c: sorry, no multiple ions in this version
```

**Comment by nbassler** [comment]
so I wonder what @jakobtoftegaard intended here
- with the strange "advanced dose" also found in pytripgui: in a plan different projectiles can be set up. Fields may also have different ions set.
I suspect, using this option will actually create multiple TRiP98 plans, for a single pytrip plan.

If that is the case, @grzanka, I might propose to remove this feature entirely, since this is rather confusing and bloats the API. Strategy: simplify API, but concentrate on making the basics work.

Related to https://github.com/pytrip/pytripgui/issues/116

**Comment by jakobtoftegaard** [comment]
I am not 100 % sure :), but I think it is for multi ions plans. However, as far as I remember it resulted is very poor dose distribution and might not be useful, so feel free to remove it.

**Comment by grzanka** [comment]
I also like the concept of simplifying API

**Comment by nbassler** [comment]
ok, thanks.
