### ISSUE TITLE
tripexecuter: no real ripple-filter support

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#347]
Currently it can only be specified by loading appropiate DDD/SPC files. However, it may also affect the "scancap" command in TRiP98.

As a user I would expect some attribute in pte.TripPlan() class where this can be specified.

**Comment by TokePrintz** [comment]
The only difference in "scancap" from using a RiFi or not is the "rifi()" option but that doesn't actually do anything apart from reminding the user later that a RiFi was used.
The biggest difference between using a RiFi or not (apart from the loading of the corresponding files) is the "zsteps()" option in the "field" command. After all, one typically uses a RiFi to lower that particular value.

**Comment by nbassler** [comment]
@TokePrintz just to double check: 
- rifi() option takes an argument (the thickness I guess), but does not affect the kernels, right? (Unlike the Bolus option, which also needs support). pte.TripPlan.rifi(string) would still be useful to have, for logging purposes.
- zsteps() is adjusted by the user, depending on which DDD file user has loaded (no magic going on in TRiP)

**Comment by TokePrintz** [comment]
Yup, correct. 
I don't know what you mean by "magic" here:-) zsteps() takes an argument, which is the distance between energy slices in depth in mm water-equivalent. As a rule of thumb we have found that it is good to use zsteps() equal to the RiFi thickness.
