### ISSUE TITLE
Issue with loading .vdx files.

### ISSUE THREAD

**Issue by Tibazz** [pytrip/pytrip#375]
The error occurs in:
https://github.com/pytrip/pytrip/blob/master/pytrip/vdx.py#L1376

I have encountered this problem a few times now when trying to load contours from a .vdx file, where the error says that con_dat[0] cannot be indexed. I checked, and it seems that it is completely empty at some times, so checking con_dat for certain lines it just yields:

```con_dat = ' ' ```

I worked around it and just put:

```if len(line) != 0:      con_dat = line.split()...```

and it seems to work for my purposes at least.

**Comment by nbassler** [comment]
Could it be that the .vdx file you try to load has empty newlines or lines containing nothing but whitespace characters?
In either case: how were the .vdx files generated?

**Comment by Tibazz** [comment]
Its very possible, it was generated from a dicom folder using dicom2trip on the trip workstation

**Comment by grzanka** [comment]
Can you send us these .vdx files by some other channel that github ?
