### ISSUE TITLE
tripexecuter: if workdir = "/tmp" then remote tarball is not copied back and throws error

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#393]
tested via pytripgui

maybe also be more specific with "workdir", and change it to "local_workdir" + "remote_workdir"

**Comment by grzanka** [comment]
I would also like to avoid using /tmp and prefer generated tmp dir or $tmpdir / $username

**Comment by nbassler** [comment]
Sure. /tmp was just an example here.

**Comment by nbassler** [comment]
tested locally with `tests/test_exec.py`
work ok. May be a remote problem only.

**Comment by nbassler** [comment]
tested remotely with modified `tests/test_exec.py`
```
        t = pte.Execute(c, v)
        t.remote = True
        t.servername = "xxxx.xxx.xx"
        t.username = "xxxxxxxx"
        t.remote_base_dir = "/tmp"
```

and it works as supposed.

**Comment by nbassler** [comment]
worksforme, must be a pytripgui issue then.
