### ISSUE TITLE
LETCube: propose to extend class with type attribute

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#395]
type may be
"DLET", "TLET", "DLET*", "DLET*", "DLETP", "TLETP", "unknown"

should these go into a dict? Or an enum?

**Comment by grzanka** [comment]
let's avoid `type` as a name, as its reserved in python.
Enum (i.e. as a subclass) is nice solution.

**Comment by nbassler** [comment]
Closed with PR #396
