### ISSUE TITLE
vdx files created by pytrip cannot be loaded by pytrip

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#403]
to reproduce:
```
import pytrip as pt
from pytrip.vdx import create_sphere

ctx = pt.CtxCube()

ctx.create_empty_cube(0, 501, 501, 501, 0.4, 0.4)

vdx = pt.VdxCube(ctx)

v0 = create_sphere(ctx, "sph0", [100, 100, 100], 10.2)
v1 = create_sphere(ctx, "sph1", [100 - 8, 100 + 4, 100], 6.2)
v2 = create_sphere(ctx, "sph2", [100 + 8, 100 + 6, 100], 5.0)

vdx.add_voi(v0)
vdx.add_voi(v1)
vdx.add_voi(v2)

ctx.write("emely000.ctx")
vdx.write("emely000.vdx")
```

then run pytripgui to inspect resulting file. Loading .vdx fails with pytrip error:
![image](https://user-images.githubusercontent.com/7140398/32058049-47ec609a-ba69-11e7-8cb7-a689645898f9.png)

**Comment by grzanka** [comment]
Which version of pytrip and of gui ?

**Comment by nbassler** [comment]
was just about to post that
![image](https://user-images.githubusercontent.com/7140398/32058140-8d3c7f4a-ba69-11e7-9f26-0680365d8869.png)

**Comment by nbassler** [comment]
instead of `re.match("foobar", line) is not None:` one might `if "foobar" in line:`

**Comment by grzanka** [comment]
@nbassler I agree
