### ISSUE TITLE
Wrong byte order in patient data

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#41]
When trying to load patient data, mentioned here: https://neptun.phys.au.dk/~bassler/TRiP/README.md:

> TST000 : Anonymous patient, not for distribution.

bytes are swapped:

```
→ cat tests/bug.py                        
from pytrip import CtxCube

c = CtxCube()
c.read("tests/TST000/TST000000.ctx")

print("shape", c.cube.shape)
print("element [0][0][0]", c.cube[0][0][0])
print("min value", c.cube.min())
print("max value", c.cube.max())

# grzanka at gajewski-dell in ~/PycharmProjects/pytrip on git:master ✖︎ [18:05:52]
→ PYTHONPATH=. python3 tests/bug.py
shape (102, 256, 256)
element [0][0][0] 6396
min value -32768
max value 32767
```

Inspecting file with hexeditor:
```
# grzanka at gajewski-dell in ~/PycharmProjects/pytrip on git:master ✖︎ [18:05:56]
→ hexdump tests/TST000/TST000000.ctx -n 20
0000000 18fc 18fc 18fc 18fc 18fc 18fc 18fc 18fc
*
0000014
```
18fc in hex means 6369 in little endian encoding and -1000 in big endian

In header file:
```
→ cat tests/TST000/TST000000.hed | grep byte_order
byte_order vms
```

Byteswapping code in pytrip (https://github.com/pytrip/pytrip/blob/master/pytrip/cube.py#L423) is following:
```
        if self.byte_order == "aix":
            cube = cube.byteswap()
```
It doesn't swap bytes for vms byte order.

Swapping the bytes or changing byte order to aix would solve the problem

**Comment by nbassler** [comment]
This does not make sense.

VMS is little endian encoding.
AIX is big endian encoding.

CBS303 has "vms" in the .hed, but when you look at the data, it is big endian encoding.
This means, the CBS303 file is broken, not PyTRiP.

**Comment by nbassler** [comment]
Original .hed says "aix". CTX md5sum is identical. So this is clearly a bad .hed file. Will update SH12A/res

**Comment by grzanka** [comment]
It is OK now, closing now.
