### ISSUE TITLE
Include range of voxel values when selecting VOI  

### ISSUE THREAD

**Issue by TokePrintz** [pytrip/pytrip#422]
For a project is required to select within a certain VOI of a patient CT only voxel values between two fixed values.

Maybe it could be neat to include this as a general PyTRiP argument, hardcode into f.ex. get_voi_cube()?  

To select values is of course trivial, like f.ex. so: 

```
def select_val_within_range(list1,low,high):
    list2 = [] 
    for i in list1:
        if(i > low and i < high):
            list2.append(i)
    return list2
```

but I cannot quickly see if to get a ctx cube output also with the positions of the selected voxels could be challenging.

**Comment by nbassler** [comment]
Is this really needed?

You can select by boolean expressions in numpy.
```
mask = myarray < 2000
mask = mask > 100
```

**Comment by nbassler** [comment]
see also our example 

https://github.com/pytrip/pytrip/blob/master/examples/example01_vdx.py

**Comment by TokePrintz** [comment]
Heh, I assume then than it is in a way already implemented :+1:
