### ISSUE TITLE
Wrong fluence normalization in plots produced by spc2pdf

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#449]
Currently fluence is not normalized by bin width. It looks like this:

![image](https://user-images.githubusercontent.com/7374733/39544698-269a9c48-4e4f-11e8-9ded-5c6ab0caed4c.png)

It should look like that:

![image](https://user-images.githubusercontent.com/7374733/39544671-156d155e-4e4f-11e8-8199-7d031e6579bd.png)

**Comment by nbassler** [comment]
did you take non-equidistant bin-width into account?

**Comment by grzanka** [comment]
Yes, I did it. The funny issue is that the energy bins are different (denser) in the part of spc where depth bins are dense.
The plot above shows "fluence per energy bin" while the plot below is adjusted for energy bin width.

**Comment by nbassler** [comment]
if you multiply with the energy bin width, then the  [ / MeV ] unit disappears (unless what they did was [ / MeV^2 ] )

**Comment by nbassler** [comment]
undo, sorry, thougth I looked at an Energy spectrum. My bad.

**Comment by grzanka** [comment]
On the first plot I multiply and there the unit will be [], while on the spectral plots (heatmaps) I do not multiply and there the unit is [ / MeV]

**Comment by grzanka** [comment]
Better now ?
![image](https://user-images.githubusercontent.com/7374733/39546262-0c5c344a-4e54-11e8-896a-9fdd601dc3f7.png)
Fix in f900c68

**Comment by nbassler** [comment]
make sense.
