### ISSUE TITLE
fix missing iterations command

### ISSUE THREAD

**Issue by TokePrintz** [pytrip/pytrip#459]
In the function  `_make_exec_opt` in _plan.py_ the iteration argument should also be written out. The iteration number is set to 500 as default in L110 but not further used.

It's an easy fix, just add ` opt += "iter({:d})".format(self.iterations)` somewhere before L534.

**Comment by nbassler** [comment]
feel free to commit a patch and setup a MR :)

**Comment by grzanka** [comment]
PR, not MR...

**Comment by nbassler** [comment]
old gitlab habit..

**Comment by TokePrintz** [comment]
Speakin as one who does not yet have any old habits on either gitlab nor github, was exactly do we mean when we say "MR" and "PR"? My guess would be that MR is merge request and PR then maybe patch request but was is the difference. I planned just to create a new branch, commit and do a merge request as I did all the other times?

**Comment by nbassler** [comment]
Stackoverflow for the win

https://stackoverflow.com/questions/22199432/pull-request-vs-merge-request

**Comment by TokePrintz** [comment]
Always! Without Stackoverflow, I would still be in the stage of hitting my fellow human beings on the head with a bone.

...I was just not 100% sure what PR meant in this context...

**Comment by nbassler** [comment]
closed via #464
