### ISSUE TITLE
Only one contour per slice

### ISSUE THREAD

**Issue by AHufnagl** [pytrip/pytrip#465]
Pytrip returns only one contour per slice. If there are several contours per slice, pytrip shows only one. For example the skin is shown as one volume, instead of a layer. Or only one of the two lungs is shown.

Skin contour Eclipse:
![skineclipse1_](https://user-images.githubusercontent.com/17451492/40842679-f60b7c74-65ae-11e8-81d2-cb255f3fe3e3.png)

Skin contour PyTRiPGUI:
![skinpytripgui_dcm_](https://user-images.githubusercontent.com/17451492/40842709-11c15bc8-65af-11e8-975c-1ffb6872fa02.png)

Lung contour Eclipse:
![lungseclipse1_](https://user-images.githubusercontent.com/17451492/40842785-426619b2-65af-11e8-8270-2646cb4b9a37.png)

Lung contour PyTRiPGUI:
![lungspytripgui_dcm_](https://user-images.githubusercontent.com/17451492/40842803-4d1d4330-65af-11e8-9bbb-552a3d9f3863.png)

**Comment by nbassler** [comment]
TRiP only supports one contour per ROI. Not sure about VDX version 2.0, if you can get any information about VDX >= 2.0 from your colleagues it would be very helpful.

With PR #466 the other dicom contours at least can be accessed in PyTRiP.

**Comment by nbassler** [comment]
@AHufnagl A public dicom dataset with similar issue is maybe this one:

https://github.com/SlicerRt/SlicerRtData/tree/master/pinnacle3-9.9-phantom-imrt
can you maybe check the "Insert" ROI in eclipse + pytripgui and see if this is the same issue?

If you are aware of other public datasets, please let us know.

**Comment by AHufnagl** [comment]
I have no access to Eclipse. I have to wait until Gracinda is back.

But what about this dataset?
https://github.com/SlicerRt/SlicerRtData/tree/master/eclipse-11-lung-contours-on-same-slices

**Comment by nbassler** [comment]
Thanks. Yes it seems to work now with #466.

![image](https://user-images.githubusercontent.com/7140398/41731425-af482d5c-757e-11e8-8b72-d26c41a450f8.png)

**Comment by nbassler** [comment]
POIs also visible now
![image](https://user-images.githubusercontent.com/7140398/41738171-a9532704-7591-11e8-8d53-bb6ccb9b53de.png)
