### ISSUE TITLE
Investigate pytrip/utils directory

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#47]
It looks that pytrip/utils has several scripts containing main methods.
Investigate if they work, and if yes, add corresponding item to setup.py, extending this piece:

```
    entry_points={
        'console_scripts': [
            'trip2dicom=pytrip.utils.trip2dicom:main',
            'dicom2trip=pytrip.utils.dicom2trip:main',
        ],
    },
```

Most of these scripts appear to be converters, add appriopriate tests.

**Comment by nbassler** [comment]
- [ ] Check what code is working
- [ ] prepare tests: supply input files/arguments so tests may execute
- [ ] Add the test code
- [ ] add argument parsers to main()
- [ ] add scripts to setup.py so they will be installed into PATH

**Comment by nbassler** [comment]
Related to #65

**Comment by grzanka** [comment]
Let us wait for PR #154 to be merged before closing that

**Comment by nbassler** [comment]
ok

**Comment by nbassler** [comment]
@grzanka  I think this one may be closed?

**Comment by grzanka** [comment]
Yes, it can be closed
