### ISSUE TITLE
Generating spherical PTV: At first and last slice, same line written out twice

### ISSUE THREAD

**Issue by TokePrintz** [pytrip/pytrip#472]
I generate .ctx and .vdx files with a spherical target as contour in the latter using the following code snip:

```
    # create the CT cube with constant HU value corresponding to lung
    my_ctx = pt.CtxCube()
    my_ctx.basename = patient_name  # give a name to the ctx file to be generated doing planning   
    my_ctx.create_empty_cube(value=-400, dimx=80, dimy=80, dimz=80, pixel_size=1.0, slice_distance=1.0, slice_offset=0.0)  #TODO:ctsteps(1,1,1) is probably too fine!

    # create a sphere as PTV and add it to VdxCube
    my_ptv = pt.vdx.create_sphere(my_ctx, 'PTV', [40,40,depth], 20.0)
    my_vdx = pt.VdxCube()
    my_vdx.basename = patient_name  # give a name to the vdx file to be generated doing planning
    my_vdx.add_voi(my_ptv)
```

but I have discovered that the first and last slice in the .vdx file for the contour has the line with the coordinates repeated:

```
slice 0
slice_in_frame 0.000
thickness 2.000 reference start_pos -1.000 stop_pos 1.000
number_of_contours 1
contour 0
internal false
number_of_points 1
 64.0000 64.0000 0.0000 0.0000 0.0000 0.0000
 64.0000 64.0000 0.0000 0.0000 0.0000 0.0000
```

which results in an error from TRiP98 in the planning phase. By manually deleting the repeated line in the first and last slice, I can run the plan using the generated .exec file.

The error must occur in vdx.py L606-L607, which handles the r2 == 0.0 case, e.g. the slices of the outmost parts of the sphere, where the contour is just a single point (it is this single point that is written out twice), but the code is so short and simple that I really cannot see where something could go wrong...

**Comment by nbassler** [comment]
properly related to contour_closed...

The VDX is regarded as a closed contour, which means the last point will be repeated when writing to voxelplan format.

Not sure what would be a proper way to handle this. 
a) Possibly we need a special case for closed contours which terminate in a point in a slice.
b) prevent create_sphere to make single points in slices.
