### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ljelen** [pytrip/pytrip#492]
test/base.py:
get_files()
returns wrong path
FileNotFoundError: [Errno 2] No such file or directory: 'tests/res/TST003'

`dirname = os.path.join('tests', 'res') `
has to be chage to 
```
dir_path = os.path.dirname(os.path.realpath(__file__))
dirname = os.path.join(dir_path, 'res')
```

**Comment by grzanka** [comment]
In which situation the error appears ?
I ran tests via:
```
PYTHONPATH=. python3 tests/test_dos.py
```
and everything seems correct.

**Comment by ljelen** [comment]
OK, now it works.
I've tried to run test from 'test' directory, that's why it could not find the relative path 'tests/res/TST003'.
This is not a bug nor a problem if test are meant to run only from top folder.
With direct path you can run it from any folder.

**Comment by nbassler** [comment]
@ljelen Welcome to the pytrip project :-)

**Comment by grzanka** [comment]
The tests should be run from the top folder. This also simplifies usage of the tools like tox and pytest. Can I close the issue ?
