### ISSUE TITLE
Error while reading dcm file

### ISSUE THREAD

**Issue by ljelen** [pytrip/pytrip#494]
An error occurred while trying to read the .dcm file with (ctx.py | read_dicom) 

> pytrip.error.InputError: "Data doesn't contain ct data"

.dcm file:
https://drive.google.com/open?id=1CU8n8LP_svrEPgSrSSHLPULdPTnBh86p
from this repository:
https://github.com/Slicer/SlicerTestingData

**Comment by nbassler** [comment]
Are you sure you are trying to open a proper CT file with images in it?

```
        if "images" not in dcm:
            raise InputError("Data doesn't contain ct data")
```

Happens to me typically when I try to load a 'rtstruct' as ctx.

**Comment by grzanka** [comment]
Interesting, when inspecting this file with dcmtk toolkit (https://dicom.offis.de/dcmtk.php.en) it seems that it is a valid CT data. See [dcmdump.log](https://github.com/pytrip/pytrip/files/3049215/dcmdump.log) obtained with following command:
```
dcmdump 36.dcm > dcmdump.log
```

Detection whether file is valid CT data is done by checking for presence of `Images` tag in DICOM dictionary, see https://github.com/pytrip/pytrip/blob/master/pytrip/ctx.py#L53

```
        if "images" not in dcm:
            raise InputError("Data doesn't contain ct data")
        if not self.header_set:
            self._set_header_from_dicom(dcm)
```

As can be seen from the dump, such tag is missing.

**Comment by nbassler** [comment]
I could not download the linked dcm file.

**Comment by grzanka** [comment]
@ljelen are you correctly calling `read_dicom` method ?

It is a bit unclear from the documentation. You should neither pass filename nor a dicom object from pydicom library.

The correct way can be seen in dicom2trip file, see https://github.com/pytrip/pytrip/blob/master/pytrip/utils/dicom2trip.py#L52

```
    # import DICOM
    dcm = pt.dicomhelper.read_dicom_dir(parsed_args.dicom_dir)

    if 'images' in dcm:
        c = pt.CtxCube()
        c.read_dicom(dcm)
```

or:

```
>>> import pytrip as pt
>>> dcm = pt.dicomhelper.read_dicom_dir("/home/grzanka/PycharmProjects/testdata/DICOM/eclipse-8.1.20-phantom-prostate/Original")
>>> dcm.keys()
dict_keys(['rtplan', 'rtdose', 'rtss', 'images'])
>>> c = pt.CtxCube()
>>> c.read_dicom(dcm)
>>> 
```

**Comment by ljelen** [comment]
@nbassler this link should works: randlab.cba.pl/36.dcm
I've tried to run  dicom2trip but it also wasnt work
@grzanka ok, now i run with that code:


 ```
dir_path = os.path.dirname(os.path.realpath(__file__))
dicom_path = os.path.join(dir_path, 'dcmcat')
print(os.listdir(dicom_path))
dcm = pt.dicomhelper.read_dicom_dir(dicom_path)
print(dcm.keys())
if 'images' in dcm:
     ctDicom = pt.CtxCube()
     ctDicom.read_dicom(dcm)
```
Now there is another problem:

> Traceback (most recent call last):
>   File "/home/deerjelen/PycharmProjects/myPytripTests/main.py", line 40, in <module>
>     main()
>   File "/home/deerjelen/PycharmProjects/myPytripTests/main.py", line 24, in main
>     ctDicom.read_dicom(dcm)
>   File "/home/deerjelen/App/anaconda3/envs/myPytripTests/lib/python3.6/site-packages/pytrip/ctx.py", line 65, in read_dicom
>     if self.slice_pos[1] < self.slice_pos[0]:
> IndexError: list index out of range

**Comment by ljelen** [comment]
#495
