### ISSUE TITLE
Subsequent calls to get_voi_cube cause an error

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#505]
One user (Kinga Jelen) reported that DVH calculation in pytrip seems to be broken.
I've reduced the use case to the following code, tested with pytrip98 v2.5.5:
```
import pytrip as pt
from pytrip.volhist import VolHist 
dos_cube = pt.DosCube()
dos_cube.read("TST000000.phys.dos")
ctx_cube = pt.CtxCube()
ctx_cube.read("TST000000.hed")
vdx_cube = pt.VdxCube(ctx_cube)
vdx_cube.read("TST000000.vdx")
target_voi = vdx_cube.get_voi_by_name('CTV')
dvh = VolHist(dos_cube, target_voi)  # this one works
dvh2 = VolHist(dos_cube, target_voi)  # this one doesn't
```

![image](https://user-images.githubusercontent.com/7374733/73446374-e9fdd480-435c-11ea-836e-db0ab2a389d2.png)

**Comment by grzanka** [comment]
It seems first of all that the method `get_voi_cube` from `Vdx` class (see https://github.com/pytrip/pytrip/blob/v2.5.5/pytrip/vdx.py#L668) has two problems:

1. It uses some caching mechanism to store the values calculated upon first execution in `self.voi_cube`. I am not sure if this is the best choice, I'd suggest using some native python mechanism for that, like LRU cache (https://docs.python.org/3/library/functools.html)

2. On the first execution `self.voi_cube` is set to object of `DosCube` type (https://github.com/pytrip/pytrip/blob/v2.5.5/pytrip/vdx.py#L690)  On subsequent calls `self.voi_cube.max()` is called. It should be replaced with `self.voi_cube.cube.max()` to be a working code.

**Comment by grzanka** [comment]
I suggest to add a comment in the code to consider using LRU cache and fixing issue described in point 2.

**Comment by ljelen** [comment]
#506
