### ISSUE TITLE
Write out beams-eye-view (bev) file

### ISSUE THREAD

**Issue by TokePrintz** [pytrip/pytrip#539]
It could sometimes be helpful for illustration purposes to plot Bragg peaks before and after some modulation done in PyTRiP. In TRiP it's pretty easy just using the field command (from TRiP documentation: "field 1 /bev(*) file(xyz.bev.gd)") but as of now this option seems not to be available in PyTRiP.

**Comment by grzanka** [comment]
It can be resolved by adding an attribute `wants_bev` to `Field` class . What about filename ? @TokePrintz  do you want to provide it as well ? Should be customized ?

**Comment by TokePrintz** [comment]
Um, filename could just be plan name as default (with option of giving ones own filename)?

**Comment by grzanka** [comment]
@TokePrintz ok, I will see if I manage to implement this quickly this evening
