### ISSUE TITLE
Investigate header file extensions

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#66]
See discussion here: https://github.com/pytrip/pytrip/pull/59#commitcomment-18805217

By looking at https://github.com/pytrip/pytrip/tree/master/tests/res/TST003 it is hard to say what is the core name and extensions for LetCube:

Which one is correct ?
- basename `tst003001.dosemlet`, header extension `.hed`, data file extension `.dos`
- basename `tst003001`, header extension `.dosemlet.hed`, data file extension `.dosemlet.dos`

@nbassler do you have an opinion ?

**Comment by nbassler** [comment]
From TRiP point of view, it should be basename `tst003001`, and the file extension is `.dosemlet.hed`. and `.dosemlet.dos`. LET cubes should also be handled differently than dos cubes when plotting, and the only clear evidence that this is a LET cube is the fileextension (and guessing by looking at the data). AFAIK there is no hint in the .hed file whether this is a dose or LET cube.

**Comment by nbassler** [comment]
@grzanka this one may be closed?

**Comment by grzanka** [comment]
@nbassler not yet

**Comment by nbassler** [comment]
@grzanka I am not sure why this is still open?

**Comment by grzanka** [comment]
It is open because current implementation (v1.2.2) has extension `.dos` for LET data cube file. See:
https://github.com/pytrip/pytrip/blob/v1.2.2/pytrip/let.py#L38

```
class LETCube(Cube):
(...)
    data_file_extension = "dos"
```

This also means that currently `parse_path` method of Cube class: https://github.com/pytrip/pytrip/blob/master/pytrip/cube.py#L499
thinks that file with `.dos` extension can be either dose cube or let cube.

Also right now all header files have univeral extension `.hed`

We also assume currently that `filename = core_name + extension` and when reading a cube we need two files:
 - `corename +'.hed'`
 - `corename + data_file_extension`

This means we can read for example pair of file `1.hed` + `1.ctx`, but we do not support reading `2.hed` + `1.ctx`. Both files currently needs to have same corename.

To fix this issue following things has to implemented:
 - change data_file_extension for LETCube to `dosemlet.dos`
 - introduce header extension specific to a data class: `dosemlet.hed` for LETCube and `.hed` for all other classes

**Comment by nbassler** [comment]
this sounds correct to me.

**Comment by nbassler** [comment]
- [ ] reminder to also fix cubeslice TODO
