### ISSUE TITLE
Combine CT information (.ctx cube) with dose maps (.dos cube) in one DICOM entity 

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#67]
Such a script which takes CTX + DOS cube and is producing DICOM output can be combined with gMocren which expects CT + dose information in single DICOM unit.

**Comment by grzanka** [comment]
The purpose of this is to display anatomical structure together with dose maps.
Another approach would be to convert .dos cube to gMocren dose file format.

**Comment by nbassler** [comment]
DICOM dose maps and CT HU data are stored in different files (Leszek)
