### ISSUE TITLE
Project logo

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#8]
Would be nice to use it instead of pytrip organization avatar

**Comment by nbassler** [comment]
I guess there should be some sort of mushroom in that logo. :mushroom:

**Comment by grzanka** [comment]
Python eating nuclear mushroom ?

**Comment by nbassler** [comment]
Perhaps we may find someonw who can draw an icon-compatible logo with a python curled up around a mushroom.

**Comment by nbassler** [comment]
![img_20170225_230116_3](https://cloud.githubusercontent.com/assets/7140398/23335910/b1f01432-fbbf-11e6-89bb-8ad42e483474.png)
