### ISSUE TITLE
Improve documentation, adding proper install and contribution guide

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#85]

**Comment by nbassler** [comment]
Prerequisites are missing. E.g. `$ sudo apt-get install python-pip` which will automatically get the dependencies.

Install guide should be clear when to use `$ sudo` 
(I here assume Debian/Redhat user will be able to translate that to root user. This is probably rather the case, than assuming Ubuntu users being able to translate `# <command>` to `$ sudo <command>`.)

**Comment by grzanka** [comment]
Is it better now ? See https://github.com/pytrip/pytrip/tree/feature/88-documentation-upgrade
I still need to improve this one: https://github.com/pytrip/pytrip/blob/feature/88-documentation-upgrade/INSTALL.rst but I think it can be done later.
Can this one https://github.com/pytrip/pytrip/pull/86 be merged ?

**Comment by nbassler** [comment]
Better, yes. 

Here some cosmetics:

 - "First, be sure you have python and pip installed." ->  "First, be sure you have **python** and **python-pip** installed."
 - Debian testing has also a name and number. Some day testing, won't be testing anymore.. So, "**Debian 9** "Stretch" (currently known as 'testing')"
 - "We assume..." -> "We recommend ... In this case ..." 
 - Boldface the recommended linux distros "**Ubuntu 16.04** or newer"
 - "this command will install the pytrip library for all users on your system "  (add the word "library")

**Comment by nbassler** [comment]
p.s.: should we stress that both python2 and python3 may be installed simulataneously? Only python2 is  OK with the GUI.
