### ISSUE TITLE
Provide detailed and clean installation instruction 

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#90]
It should be tested on reasonable set of Linux distributions.
Summary of python&pip versions can be found here: https://github.com/grzanka/python-pip-versions

Important stuff should go on the top, less on the bottom.

As it will grow, it should be splitted into more pages.

**Comment by nbassler** [comment]
Agree to add a few major distros (in particular windoze).
Then let it expand as users require or request it.
