### ISSUE TITLE
Fix broken links on readthedocs

### ISSUE THREAD

**Issue by grzanka** [pytrip/pytrip#93]
Go to webpage https://pytrip.readthedocs.io/en/latest/readme.html

Scroll down and find link to contribution guide at the bottom.

It points to https://pytrip.readthedocs.io/en/latest/CONTRIBUTING.rst
When going there we see non-existing page.

Same link on github (on https://github.com/pytrip/pytrip)  works well, it is pointing to: https://github.com/pytrip/pytrip/blob/master/CONTRIBUTING.rst

**Comment by nbassler** [comment]
could point to local section instead.

**Comment by nbassler** [comment]
fixed in #165
