### ISSUE TITLE
VdxCube() seems to be broken

### ISSUE THREAD

**Issue by nbassler** [pytrip/pytrip#96]
Python3:
```
>>> v.read("TST000000.vdx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pytrip/vdx.py", line 95, in read
    self.read_vdx(path)
  File "/usr/local/lib/python3.5/dist-packages/pytrip/vdx.py", line 121, in read_vdx
    i = v.read_vdx(content, i)
  File "/usr/local/lib/python3.5/dist-packages/pytrip/vdx.py", line 498, in read_vdx
    self.name = string.join(line.split()[1:], ' ')
AttributeError: module 'string' has no attribute 'join'
```

Python2:
```
>>> v.read("TST000000.vdx")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 95, in read
    self.read_vdx(path)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 121, in read_vdx
    i = v.read_vdx(content, i)
  File "/usr/local/lib/python2.7/dist-packages/pytrip/vdx.py", line 512, in read_vdx
    key = int((float(s.get_position()) - min(self.cube.slice_pos)) * 100)
AttributeError: 'NoneType' object has no attribute 'slice_pos'
```

**Comment by nbassler** [comment]
These issues can probably be fixed with a dirty hack, however on the long run I recommend to rewrite this part to something more clean.  See #97

**Comment by grzanka** [comment]
I've tested with this file: https://github.com/pytrip/pytrip/blob/master/tests/res/TST003/tst003000.vdx
and it seems to work:

```
→ python3.4
Python 3.4.3 (default, Sep 14 2016, 12:36:27) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pytrip
>>> from pytrip.vdx import VdxCube
>>> v = VdxCube("")
>>> v.read("tests/res/TST003/tst003000.vdx")
['voi', 'target', 'type', '1', '#subvoi', '1']
>>> 
```

@nbassler  can you reproduce the same problem with tests/res/TST003/tst003000.vdx file ?
From your message its not clear what is v object. Can you copy-paste full session, from starting python interpreter ?

**Comment by grzanka** [comment]
Are there two different formats of VDX files ?

It looks that if I use VDX as described above, then method **read_vdx_old** from class **Voi** is used:
https://github.com/pytrip/pytrip/blob/feature/96-vdx-broken/pytrip/vdx.py#L480

This method seems to read without complaines files like https://github.com/pytrip/pytrip/blob/master/tests/res/TST003/tst003000.vdx

If I imply using other method, i.e. by running following code:
```
from pytrip.vdx import VdxCube

v = VdxCube("")
v.version = "2.0"
v.read("tests/res/TST003/tst003000.vdx")
```

Then method **read_vdx** from **Voi** class is activated:
https://github.com/pytrip/pytrip/blob/feature/96-vdx-broken/pytrip/vdx.py#L498

This method gives similar errors as @nbassler reported initially.

The problem I see is that **read_vdx** seem to read files in different format than https://github.com/pytrip/pytrip/blob/master/tests/res/TST003/tst003000.vdx

**Comment by nbassler** [comment]
Yes, there are at least two formats.

**Comment by grzanka** [comment]
It seems bug disappears if user loads CT cube first.
Following code works:

```
from pytrip.vdx import VdxCube
from pytrip.ctx import CtxCube

c = CtxCube()
c.read("TST000000")

v = VdxCube("", c)
v.read("TST000000.vdx")
```
